#!/usr/bin/env ruby
# Run Kitchenplan.

require 'pathname'

if ENV['USER'] == 'root'
  abort "Run this as a normal user, I'll sudo if I need to."
end


########################################

abort "Don't run this as root!" if Process.uid == 0
abort <<-EOABORT unless `groups`.split.include? "admin"
This script requires the user #{ENV['USER']} to be an Administrator.
EOABORT

# Put us where we belong, in the root dir of our kitchenplan repo.

Dir.chdir Pathname.new(__FILE__).realpath + ".."

# Flags
require 'optparse'

options = {}
OptionParser.new do |opts|
    opts.banner = 'Usage: kitchenplan [options]'

    opts.on("-d", "--debug", "Show debug information") do |debug|
        options[:debug] = debug
    end

    opts.on("-c", "--update-cookbooks", "Update the Chef cookbooks") do |update_cookbooks|
        options[:update_cookbooks] = update_cookbooks
    end

    options[:soloist] = true
    opts.on("--[no-]soloist", "Run soloist (defaults to yes)") do |soloist|
        options[:soloist] = soloist
    end

    options[:update] = true
    opts.on("--[no-]update", "Run the kitchenplan update (defaults to yes)") do |update|
        options[:update] = update
    end

    opts.separator ""
    opts.separator "Common options:"

    opts.on_tail("-h", "--help", "Show this message") do
        puts opts
        exit
    end

    opts.on_tail("--version", "Show version") do
        puts "1.0.1"
        exit
    end

end.parse!

# Bootstrapping dependencies
sudo "sudo gem install bundler --no-rdoc --no-ri" unless Kernel.system "gem query --name-matches '^bundler$' --installed > /dev/null 2>&1"
normaldo "rm -rf .bundle/config"
normaldo "bundle install --binstubs bin --path .bundle --deployment --local --no-cache #{(options[:debug] ? '--verbose' : '--quiet')}"

# Add local deps to the load path.

require "rubygems"
require "bundler/setup"

# Trying to get some metrics for usage, just comment out if you don't want it.
ohai 'Sending a ping to Google Analytics to count usage'
require 'Gabba'
Gabba::Gabba.new("UA-46288146-1", "github.com").event("Kitchenplan", "Run", ENV['USER'])

# Generate the soloist config
$: << File.join((File.expand_path("../", Pathname.new(__FILE__).realpath)), "/lib")
require 'json'
require "kitchenplan/config"
config = Kitchenplan::Config.new
soloistrc = {}
soloistrc["cookbook_paths"] = ["#{Dir.pwd}/vendor/cookbooks"]
soloistrc["recipes"] = config.config['recipes']
soloistrc["node_attributes"] = config.config['attributes']
File.open("soloistrc", 'w') do |out|
    YAML.dump(soloistrc, out)
end

# Possibly updating the cookbooks

if config.platform == "debian"
    git_install_command = ["sudo" ,"apt-get", "install", "-y", "git" ]
    warn git_install_command.join(" ") if options[:debug]
    unless system *git_install_command
        abort "Can't install git. Run using --debug if you need more information."
    end
end

# Installing
normaldo "bin/librarian-chef install --clean #{(options[:debug] ? '--verbose' : '--quiet')}" unless File.exists?("cookbooks")
normaldo "bin/librarian-chef update #{(options[:debug] ? '--verbose' : '')}" if options[:update_cookbooks]

if options[:update_cookbooks]
    librarian_command = ["bin/librarian-chef", "update", "--verbose" ]
    warn librarian_command.join(" ") if options[:debug]
    unless system *librarian_command
        abort "Can't update Chef cookbooks with librarian-chef. Run using --debug if you need more information."
    end
end

# Run soloist

exit 0 unless options[:soloist]

soloist_command = ["bin/soloist"]
ENV["LOG_LEVEL"] = "error"
ENV["LOG_LEVEL"] = "debug" if options[:debug]
warn soloist_command.join(" ") if options[:debug]
unless system *soloist_command
    abort "There was a problem running solist. Run using --debug for more information"
end
